// @ts-check

// One sidebar per keyboard. Each keyboard lives in its own folder under
// docs/, so adding a new board means: make the folder, add a sidebar entry
// here, and add a navbar item in docusaurus.config.js.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  crossesV2: [{ type: 'autogenerated', dirName: 'crosses-v2' }],
};

export default sidebars;
