// @ts-check

// The sidebar mirrors the docs/ folder structure; ordering comes from
// sidebar_position in each page's frontmatter and _category_.json files.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
